FROM ghcr.io/coqui-ai/tts-cpu:7b5c8422c83758e67ab0e2d0d3559a12a8321732

ADD cleaners.py /root/TTS/tts/utils/text/cleaners.py
ADD convert.py /root/TTS/server/convert.py
ADD scale_stats.npy /storage/TTS/scale_stats.npy
